services:
  backend:
    build: ./mern-demo/server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://<username>:<password>@cluster0.nw18gtl.mongodb.net/cloud_lab?appName=Cluster0

  frontend:
    build: ./mern-demo/client
    ports:
      - "3000:3000"
    depends_on:
      - backend
